import json
from deepdiff import DeepDiff

def validate_json(expected_json_str, predicted_json_str):
    try:
        expected = json.loads(expected_json_str)
        predicted = json.loads(predicted_json_str)
    except Exception as e:
        return {"valid": False, "error": f"Invalid JSON: {e}"}

    diff = DeepDiff(expected, predicted, ignore_order=True)

    feedback = []
    for category, changes in diff.items():
        for path, change in (changes.items() if isinstance(changes, dict) else enumerate(changes)):
            feedback.append(f"{category}: {path} → {change}")

    result = {
        "valid": len(diff) == 0,
        "differences": diff.to_dict(),
    }

    if result["valid"]:
        result["feedback"] = "Both the JSONs match exactly"
    else:
        result["feedback"] = "The output JSON does not match the expected JSON.\n- " + "\n- ".join(feedback)

    return result
expected_json, extracted_json = r"""{
  "extracted_invoice_values": {
    "invoice_number": "41854 2024-2025",
    "patient_name": "mst. Jaksh Sandeep Adarkar",
    "services": [
      {
        "service": "Regular Consultation by. Shailesh R Barot",
        "amount": 500,
        "quantity": 1,
        "department": "consultation",
        "unit": null,
        "mrp": 0,
        "cgst": 0,
        "cgst_type": null,
        "sgst": 0,
        "sgst_type": null,
        "gst": 0,
        "gst_type": null
      }
    ],
    "total_amount": 500,
    "doctor_name": "Dr. Shailesh R Barot",
    "facility": "ANKUR PEDIATRIC MULTISPECIALITY HOSPITAL LLP, 204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303, Mob: - 8975778866/ 9921487700, Reg No.: WCMC/C-H-123/2013",
    "invoice_date": "22/01/2025",
    "payment_mode": null,
    "patient_age": "2.3 Years",
    "patient_gender": "Male",
    "patient_contact": null,
    "cgst": 0,
    "cgst_type": null,
    "sgst": 0,
    "sgst_type": null,
    "gst": 0,
    "gst_type": null,
    "discount": 0,
    "mrp": 0,
    "round_off": 0
  },
  "raw_text": "=== CUSTOMER INFORMATION ===\nPatient Name :: mst. Jaksh Sandeep\nAdarkar\nPatient Name :: mst. Jaksh Sandeep\nAdarkar\n\n=== SUPPLIER INFORMATION ===\nADDRESS: MULTISPECIALITY\nPEDIATRIC\nANKUR\n204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nSTREET: 204, Thakur Tower, Raja C.S. Marg,\nCITY: Mirar (W)\nZIP_CODE: 401303\nADDRESS_BLOCK: 204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nNAME: HOSPITAL LLP\nMULTISPECIALITY\nNAME: ankur\nVENDOR_ADDRESS: MULTISPECIALITY\nPEDIATRIC\nANKUR\n204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nVENDOR_NAME: HOSPITAL LLP\nMULTISPECIALITY\nVENDOR_NAME: ankur\nMob:: 8975778866/\nVENDOR_PHONE: 9921487700\n\n=== ADDITIONAL DOCUMENT DETAILS ===\n\nAmount Paid\n:: 500.00 Bill Date :: 22/01/2025 Bill No. :: 41854 2024-2025 SUBTOTAL: Five Hundred Only Net Amount\n:: 500.00 Amount Receivable\n:: 500.00 Amount Receivable\n:: 500.00 TOTAL: Five Hundred Only No:: 41 Time: 9: 00 Reg No.:: WCMC/C-H-123/2013 Time: :09:29 PM UHID No. :: 42760 Gender / Age :: Male / 2.3 Years Dept. :: Paediatric Consulting Doc. :: Dr. Shailesh R Barot Referred By :: Self Bill Generated by :: Varsha Printed On Date & Time :: 22/01/2025 9: 29PM Activation Key:: 036900042760 SNo.: 1 Service: Regular Consultation by Dr.\nShailesh R Barot Rate: 500.00 Qty: 1 Amount: 500.00  | \n\nRaw Text Content:\nCultivating a better Tomorrow\nNo:41 Time 9:00\nANKUR PEDIATRIC MULTISPECIALITY HOSPITAL LLP\nankur\n204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nP0250-2503059/2506508 Mob: - 8975778866/ 9921487700\nReg No.: WCMC/C-H-123/2013\nBILL CUM RECEIPT\nBill No.\n: 41854 2024-2025\nBill Date\n: 22/01/2025\nTime\n:09:29 PM\nPatient Name\n: mst. Jaksh Sandeep\nUHID No.\n: 42760\nAdarkar\nGender / Age\n: Male / 2.3 Years\nDept.\n: Paediatric\nConsulting Doc.\n: Dr. Shailesh R Barot\nReferred By\n: Self\nSNo. Service\nRate\nQty\nAmount\n1\nRegular Consultation by Dr.\n500.00\n1\nShailesh R Barot\n500.00\nFive Hundred Only\nNet Amount\n:\n500.00\nAmount Receivable\nFive Hundred Only\n:\n500.00\nAmount Paid\nBill Generated by : Varsha\n:\n500.00\nThis bill was printed using Caresoft HIS www.caresoft.co.in by : Varsha\nPrinted On Date & Time : 22/01/2025 9:29PM\nAppointment App Android:\nIOS:\nAuthorized Signatory\nActivation Key: 036900042760\n0U2140//00"
}""", r"""{
  "extracted_invoice_values": {
    "invoice_number": "41854 2024-2025",
    "patient_name": "mst. Jaksh Sandeep Adarkar",
    "services": [
      {
        "service": "Regular Consultation by Dr. Shailesh R Barot",
        "amount": 500,
        "quantity": 1,
        "department": "consultation",
        "unit": null,
        "mrp": 0,
        "cgst": 0,
        "cgst_type": null,
        "sgst": 0,
        "sgst_type": null,
        "gst": 0,
        "gst_type": null
      }
    ],
    "total_amount": 500,
    "doctor_name": "Dr. Shailesh R Barot",
    "facility": "ANKUR PEDIATRIC MULTISPECIALITY HOSPITAL LLP, 204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303, Mob: - 8975778866/ 9921487700, Reg No.: WCMC/C-H-123/2013",
    "invoice_date": "22/01/2025",
    "payment_mode": null,
    "patient_age": "2.3 Years",
    "patient_gender": "Male",
    "patient_contact": null,
    "cgst": 0,
    "cgst_type": null,
    "sgst": 0,
    "sgst_type": null,
    "gst": 0,
    "gst_type": null,
    "discount": 0,
    "mrp": 0,
    "round_off": 0
  },
  "raw_text": "=== CUSTOMER INFORMATION ===\nPatient Name :: mst. Jaksh Sandeep\nAdarkar\nPatient Name :: mst. Jaksh Sandeep\nAdarkar\n\n=== SUPPLIER INFORMATION ===\nADDRESS: MULTISPECIALITY\nPEDIATRIC\nANKUR\n204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nSTREET: 204, Thakur Tower, Raja C.S. Marg,\nCITY: Mirar (W)\nZIP_CODE: 401303\nADDRESS_BLOCK: 204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nNAME: HOSPITAL LLP\nMULTISPECIALITY\nNAME: ankur\nVENDOR_ADDRESS: MULTISPECIALITY\nPEDIATRIC\nANKUR\n204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nVENDOR_NAME: HOSPITAL LLP\nMULTISPECIALITY\nVENDOR_NAME: ankur\nMob:: 8975778866/\nVENDOR_PHONE: 9921487700\n\n=== ADDITIONAL DOCUMENT DETAILS ===\n\nAmount Paid\n:: 500.00 Bill Date :: 22/01/2025 Bill No. :: 41854 2024-2025 SUBTOTAL: Five Hundred Only Net Amount\n:: 500.00 Amount Receivable\n:: 500.00 Amount Receivable\n:: 500.00 TOTAL: Five Hundred Only No:: 41 Time: 9: 00 Reg No.:: WCMC/C-H-123/2013 Time: :09:29 PM UHID No. :: 42760 Gender / Age :: Male / 2.3 Years Dept. :: Paediatric Consulting Doc. :: Dr. Shailesh R Barot Referred By :: Self Bill Generated by :: Varsha Printed On Date & Time :: 22/01/2025 9: 29PM Activation Key:: 036900042760 SNo.: 1 Service: Regular Consultation by Dr.\nShailesh R Barot Rate: 500.00 Qty: 1 Amount: 500.00  | \n\nRaw Text Content:\nCultivating a better Tomorrow\nNo:41 Time 9:00\nANKUR PEDIATRIC MULTISPECIALITY HOSPITAL LLP\nankur\n204, Thakur Tower, Raja C.S. Marg, Mirar (W) 401303\nP0250-2503059/2506508 Mob: - 8975778866/ 9921487700\nReg No.: WCMC/C-H-123/2013\nBILL CUM RECEIPT\nBill No.\n: 41854 2024-2025\nBill Date\n: 22/01/2025\nTime\n:09:29 PM\nPatient Name\n: mst. Jaksh Sandeep\nUHID No.\n: 42760\nAdarkar\nGender / Age\n: Male / 2.3 Years\nDept.\n: Paediatric\nConsulting Doc.\n: Dr. Shailesh R Barot\nReferred By\n: Self\nSNo. Service\nRate\nQty\nAmount\n1\nRegular Consultation by Dr.\n500.00\n1\nShailesh R Barot\n500.00\nFive Hundred Only\nNet Amount\n:\n500.00\nAmount Receivable\nFive Hundred Only\n:\n500.00\nAmount Paid\nBill Generated by : Varsha\n:\n500.00\nThis bill was printed using Caresoft HIS www.caresoft.co.in by : Varsha\nPrinted On Date & Time : 22/01/2025 9:29PM\nAppointment App Android:\nIOS:\nAuthorized Signatory\nActivation Key: 036900042760\n0U2140//00"
} """

# x,y = json.loads(expected_json), json.loads(extracted_json)

# diff = DeepDiff(x, y, ignore_order=True)
# print(diff.to_dict())

result = validate_json(expected_json, extracted_json)


print(result)